/**
 * components/second-look/strings.ts — UI strings for /second-look that
 * are not in lib/copy.ts (which is frozen for this build). Short labels
 * only; the page copy itself lives in copy.secondLook.
 */

export const SL = {
  replayAll: "replay all",
  orbPrefix: "// m8:",
  dropHint: "drop a Loan Estimate here",
  readList: "// fields",
  stats: {
    payment: "Monthly P&I",
    upfront: "Upfront",
    upfrontPoints: "Points paid at closing",
    upfrontCredit: "Credit toward closing costs",
    breakeven: "Break-even",
    breakevenSub: "Months until the points option catches up",
    monthShort: "mo",
    never: "Never",
    timeline: "Months since closing",
    markerPoints: (m: string) => `Points win after month ${m}`,
    markerCredit: (m: string) => `Credit stays ahead until month ${m}`,
    rateLabel: "Rate",
  },
  live: {
    steps: ["consent", "upload", "redact", "read", "results"],
    previewFlow: "Preview the flow with the sample",
    previewNote: "Preview mode. Nothing leaves this page and nothing is sent to M8.",
    previewSendNote: "Sending is off in preview mode.",
    noTextLayer: "Images have no text layer to scan. Draw a box over anything you want hidden before sending.",
    pdfNote: "PDF text extraction is coming. Image upload works today: for now, take a clear photo or screenshot of each page and upload that.",
    pdfRefuse: "Image upload works, PDF text extraction coming. Upload a photo or screenshot of the page instead.",
    autoMasked: "Masked automatically",
    nothingFound: "No name, address, ID, or SSN-shaped strings were detected in the text layer.",
    maskedPreview: "Masked text that would be sent",
    boxesHint: "Tap Add redaction box, then drag over the preview. Boxes are burned in before upload.",
    addCenteredBox: "Add a centered box",
    drawing: "Drawing — drag on the preview",
    boxCount: (n: number) => `${n} box${n === 1 ? "" : "es"}`,
    fileTooLarge: "That file is too large. Keep it under 10 MB.",
    unsupported: "Unsupported file. Use a PDF, PNG, or JPG.",
    compositeFailed: "Could not prepare the masked image. Try a different file.",
    payloadTooLarge: "The masked image is still over 2 MB. Try a smaller photo or a screenshot.",
    networkFailed: "Could not reach M8. Check your connection and try again.",
    pages: (n: number) => `${n} page${n === 1 ? "" : "s"}`,
    startOver: "Start over",
    back: "Back",
    tryAgain: "Try again",
    confidence: "confidence",
    summary: "// summary",
    labels: {
      trueCost: "// true cost",
      negotiable: "// negotiable vs. fixed",
      cashToClose: "// cash to close",
      pointsCredit: "// points vs. credit",
      questions: "// questions",
      rate: "Interest rate",
      apr: "APR",
      points: "Points",
      lenderCredits: "Lender credits",
      sectionA: "Section A",
      sectionBC: "Sections B + C",
      cashToCloseField: "Cash to close",
      negotiableFees: "Lender-set or shoppable",
      fixedFees: "Pass-through / third-party",
      notFound: "not found",
      none: "None listed",
    },
  },
} as const;
